-- ============================================================================
-- Backend de Aplicaciones - DDL H2 (estructura inicial)
-- Nota: H2 convierte identificadores NO entrecomillados a MAYÚSCULAS.
--       Mantenemos el esquema MAIN para reflejar el "main." de SQLite.
-- ============================================================================

-- Limpieza opcional (si se re-ejecuta el script)
DROP TABLE IF EXISTS CLIENTES;
DROP TABLE IF EXISTS CONTENEDORES;
DROP TABLE IF EXISTS SOLICITUDES;


DROP SEQUENCE IF EXISTS SEQ_CLIENTES;
DROP SEQUENCE IF EXISTS SEQ_CONTENEDORES;
DROP SEQUENCE IF EXISTS SEQ_SOLICITUDES;


-- Secuencias (todas comienzan en 1)
CREATE SEQUENCE SEQ_CLIENTES START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_CONTENEDORES START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_SOLICITUDES START WITH 1 INCREMENT BY 1;


-- CLIENTES
CREATE TABLE CLIENTES
(
    CLI_ID      INT NOT NULL DEFAULT NEXT VALUE FOR SEQ_CLIENTES,
    NOMBRE      VARCHAR(255) NOT NULL,
    CORREO      VARCHAR(255) NOT NULL,
    DIRECCION   VARCHAR(255),
    TELEFONO    VARCHAR(20),
    CONSTRAINT PK_CLIENTES PRIMARY KEY (CLI_ID)
);

-- CONTENEDORES
CREATE TABLE CONTENEDORES
(
    CONT_ID     INT NOT NULL DEFAULT NEXT VALUE FOR SEQ_CONTENEDORES,
    PESO      DOUBLE NOT NULL,
    VOLUMEN    DOUBLE NOT NULL,
    ESTADO     VARCHAR(50) NOT NULL,
    CLIENTE_ID  INT,
    CONSTRAINT FK_CONTENEDORES_CLIENTES FOREIGN KEY (CLIENTE_ID) REFERENCES CLIENTES(CLI_ID),
    CONSTRAINT PK_CONTENEDORES PRIMARY KEY (CONT_ID)
);

-- SOLICITUDES
CREATE TABLE SOLICITUDES
(
    SOLI_ID     INT NOT NULL DEFAULT NEXT VALUE FOR SEQ_SOLICITUDES,
    ID_CLIENTE  INT NOT NULL,
    ID_CONTENEDOR INT NOT NULL,
    ESTADO      VARCHAR(50) NOT NULL,
    COSTO_ESTIMADO DOUBLE,
    TIEMPO_ESTIMADO INTEGER, -- en segundos
    FECHA_HORA_SALIDA TIMESTAMP,
    COSTO_FINAL DOUBLE,
    TIEMPO_REAL INTEGER, -- en segundos
    CONSTRAINT PK_SOLICITUDES PRIMARY KEY (SOLI_ID)
);

-- Índices sugeridos (optativos) para mejorar joins/búsquedas por FK
CREATE INDEX IF NOT EXISTS IX_CLIENTES_SOLICITUDES       ON SOLICITUDES(ID_CLIENTE);
CREATE INDEX IF NOT EXISTS IX_CONTENEDORES_SOLICITUDES   ON SOLICITUDES(ID_CONTENEDOR);
CREATE INDEX IF NOT EXISTS IX_SOLICITUDES_ESTADO       ON SOLICITUDES(ESTADO);
CREATE INDEX IF NOT EXISTS IX_CONTENEDORES_CLIENTES      ON CONTENEDORES(CLIENTE_ID);
