-- ============================================================================
-- Backend de Aplicaciones - DDL H2 (estructura inicial)
-- Nota: H2 convierte identificadores NO entrecomillados a MAYÚSCULAS.
--       Mantenemos el esquema MAIN para reflejar el "main." de SQLite.
-- ============================================================================

-- Limpieza opcional (si se re-ejecuta el script)
DROP TABLE IF EXISTS RUTAS;
DROP TABLE IF EXISTS TRAMOS;
DROP TABLE IF EXISTS TARIFAS;
DROP TABLE IF EXISTS DEPOSITOS;
DROP TABLE IF EXISTS CAMIONES;
DROP TABLE IF EXISTS TRANSPORTISTAS;

DROP TABLE IF EXISTS NODOS;
DROP TABLE IF EXISTS ENLACES;


DROP SEQUENCE IF EXISTS SEQ_RUTAS;
DROP SEQUENCE IF EXISTS SEQ_TARIFAS;
DROP SEQUENCE IF EXISTS SEQ_DEPOSITOS;
DROP SEQUENCE IF EXISTS SEQ_TRANSPORTISTAS;

DROP SEQUENCE IF EXISTS SEQ_NODOS;
DROP SEQUENCE IF EXISTS SEQ_ENLACES;


-- Secuencias (todas comienzan en 1)
CREATE SEQUENCE SEQ_TRAMOS START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_RUTAS START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_TARIFAS START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_DEPOSITOS START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_TRANSPORTISTAS START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_NODOS START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_ENLACES START WITH 1 INCREMENT BY 1;

-- Trigger para asignar TRAMO_ID por RUTA
--CREATE TRIGGER TRG_TRAMOS_BEFORE_INSERT
--BEFORE INSERT ON TRAMOS
--FOR EACH ROW
--AS
--BEGIN ATOMIC
--    SET NEW.TRAMO_ID = COALESCE(
--        (SELECT MAX(TRAMO_ID) + 1 FROM TRAMOS WHERE ID_RUTA = NEW.ID_RUTA),
--        1
--   );
--END;

-- TRANSPORTISTAS
CREATE TABLE TRANSPORTISTAS
(
    TRANSP_ID       INT NOT NULL DEFAULT NEXT VALUE FOR SEQ_TRANSPORTISTAS,
    NOMBRE          VARCHAR(255) NOT NULL,
    APELLIDO        VARCHAR(255) NOT NULL,
    TELEFONO        VARCHAR(20),
    CORREO          VARCHAR(255) NOT NULL,
    DIRECCION       VARCHAR(255) NOT NULL,
    ACTIVO          BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT PK_TRANSPORTISTAS PRIMARY KEY (TRANSP_ID)
);


-- CAMIONES
CREATE TABLE CAMIONES
(
    DOMINIO             VARCHAR(100) NOT NULL,
    ID_TRANSPORTISTA    INT NOT NULL,
    CAPACIDAD_PESO      DOUBLE NOT NULL,
    CAPACIDAD_VOLUMEN   DOUBLE NOT NULL,
    DISPONIBILIDAD      BOOLEAN NOT NULL,
    CONSUMO_BASE_X_KM   DOUBLE NOT NULL,
    CONSUMO_X_KM        DOUBLE NOT NULL,
    CONSTRAINT FK_CAMIONES_TRANSPORTISTAS FOREIGN KEY (ID_TRANSPORTISTA) REFERENCES TRANSPORTISTAS(TRANSP_ID),
    CONSTRAINT PK_CAMIONES PRIMARY KEY (DOMINIO)
);


-- TARIFAS
CREATE TABLE TARIFAS
(
    TARIFA_ID           INT NOT NULL DEFAULT NEXT VALUE FOR SEQ_TARIFAS,
    VOLUMEN_MIN         DOUBLE NOT NULL,
    VOLUMEN_MAX         DOUBLE NOT NULL,
    COSTO_BASE_X_KM     DOUBLE NOT NULL,
    CONSUMO_X_KM        DOUBLE NOT NULL,
    PRECIO_COMBUSTIBLE  DOUBLE NOT NULL,
    FECHA_DESDE         TIMESTAMP NOT NULL,
    FECHA_HASTA         TIMESTAMP,
    CONSTRAINT PK_TARIFAS PRIMARY KEY (TARIFA_ID)
);


-- DEPOSITOS
CREATE TABLE DEPOSITOS
(
    DEPO_ID                 INT NOT NULL DEFAULT NEXT VALUE FOR SEQ_DEPOSITOS,
    NOMBRE                  VARCHAR(255) NOT NULL,
    DIRECCION               VARCHAR(255) NOT NULL,
    LATITUD                 DOUBLE NOT NULL,
    LONGITUD                DOUBLE NOT NULL,
    COSTO_ESTADIA_DIARIO    DOUBLE NOT NULL,
    CONSTRAINT PK_DEPOSITOS PRIMARY KEY (DEPO_ID)
);


-- RUTAS
CREATE TABLE RUTAS
(
    RUTA_ID                  INT NOT NULL DEFAULT NEXT VALUE FOR SEQ_RUTAS,
    ID_SOLICITUD             INT NOT NULL,
    ORIGEN_LATITUD           DOUBLE NOT NULL,
    ORIGEN_LONGITUD          DOUBLE NOT NULL,
    DESTINO_LATITUD          DOUBLE NOT NULL,
    DESTINO_LONGITUD         DOUBLE NOT NULL,
    CANTIDAD_TRAMOS          INT NOT NULL,
    CANTIDAD_DEPOSITOS       INT NOT NULL,
    -- FK lógica: RUTAS.ID_SOLICITUD -> SOLICITUDES.ID_SOLICITUD (otra base)
    CONSTRAINT PK_RUTAS PRIMARY KEY (RUTA_ID)
);

-- TRAMOS
CREATE TABLE TRAMOS
(
    TRAMO_ID            INT NOT NULL DEFAULT NEXT VALUE FOR SEQ_TRAMOS,
    ID_RUTA             INT NOT NULL,
    DOMINIO_CAMION      VARCHAR(100) NOT NULL,
    ORIGEN              INT,
    DESTINO             INT,
    ID_TARIFA           INT NOT NULL,
    TIPO                VARCHAR(50) NOT NULL,
    ESTADO              VARCHAR(50) NOT NULL,
    DISTANCIA           DOUBLE NOT NULL,
    TIEMPO_ESTIMADO     INTEGER NOT NULL, -- en segundos
    COSTO_APROXIMADO    DOUBLE NOT NULL,
    COSTO_REAL          DOUBLE,
    FECHA_HORA_INICIO   TIMESTAMP,
    FECHA_HORA_FIN      TIMESTAMP,
    CONSTRAINT FK_TRAMOS_RUTAS FOREIGN KEY (ID_RUTA) REFERENCES RUTAS(RUTA_ID),
    CONSTRAINT FK_TRAMOS_TARIFAS FOREIGN KEY (ID_TARIFA) REFERENCES TARIFAS(TARIFA_ID),
    CONSTRAINT FK_TRAMOS_ORIGEN FOREIGN KEY (ORIGEN) REFERENCES DEPOSITOS(DEPO_ID),
    CONSTRAINT FK_TRAMOS_DESTINO FOREIGN KEY (DESTINO) REFERENCES DEPOSITOS(DEPO_ID),
    CONSTRAINT FK_TRAMOS_CAMIONES FOREIGN KEY (DOMINIO_CAMION) REFERENCES CAMIONES(DOMINIO),
    CONSTRAINT PK_TRAMOS PRIMARY KEY (TRAMO_ID, ID_RUTA)
);


-- NODOS
CREATE TABLE NODOS
(
    NODO_ID     INT NOT NULL DEFAULT NEXT VALUE FOR SEQ_NODOS,
    ID_DEPOSITO INT NOT NULL UNIQUE,
    LATITUD     DOUBLE NOT NULL,
    LONGITUD    DOUBLE NOT NULL,
    G           DOUBLE,
    H           DOUBLE,
    F           DOUBLE,
    PADRE_ID    INT,
    CONSTRAINT FK_NODOS_DEPOSITOS FOREIGN KEY (ID_DEPOSITO) REFERENCES DEPOSITOS(DEPO_ID),
    CONSTRAINT PK_NODOS PRIMARY KEY (NODO_ID)
);

ALTER TABLE NODOS
ADD CONSTRAINT FK_NODOS_PADRE FOREIGN KEY (PADRE_ID) REFERENCES NODOS(NODO_ID);


-- ENLACES
CREATE TABLE ENLACES
(
    ENLACE_ID       INT NOT NULL DEFAULT NEXT VALUE FOR SEQ_ENLACES,
    ORIGEN_ID       INT NOT NULL,
    DESTINO_ID      INT NOT NULL,
    DISTANCIA       DOUBLE NOT NULL,
    TIEMPO_ESTIMADO INTEGER NOT NULL, -- en segundos
    CONSTRAINT FK_ENLACES_ORIGEN FOREIGN KEY (ORIGEN_ID) REFERENCES NODOS(NODO_ID),
    CONSTRAINT FK_ENLACES_DESTINO FOREIGN KEY (DESTINO_ID) REFERENCES NODOS(NODO_ID),
    CONSTRAINT PK_ENLACES PRIMARY KEY (ENLACE_ID)
);

-- Índices sugeridos (optativos) para mejorar joins/búsquedas por FK
CREATE INDEX IF NOT EXISTS IX_RUTAS_SOLICITUDES       ON RUTAS(ID_SOLICITUD);
CREATE INDEX IF NOT EXISTS IX_TRAMOS_RUTAS            ON TRAMOS(ID_RUTA);
CREATE INDEX IF NOT EXISTS IX_TRAMOS_TARIFAS          ON TRAMOS(ID_TARIFA);
CREATE INDEX IF NOT EXISTS IX_TRAMOS_ORIGEN           ON TRAMOS(ORIGEN);
CREATE INDEX IF NOT EXISTS IX_TRAMOS_DESTINO          ON TRAMOS(DESTINO);
CREATE INDEX IF NOT EXISTS IX_TRAMOS_CAMIONES         ON TRAMOS(DOMINIO_CAMION);
CREATE INDEX IF NOT EXISTS IX_CAMIONES_TRANSPORTISTAS ON CAMIONES(ID_TRANSPORTISTA);
