
-- Limpieza previa
DROP TABLE IF EXISTS TRAMOS CASCADE;
DROP TABLE IF EXISTS RUTAS CASCADE;
DROP TABLE IF EXISTS TARIFAS CASCADE;
DROP TABLE IF EXISTS DEPOSITOS CASCADE;
DROP TABLE IF EXISTS CAMIONES CASCADE;
DROP TABLE IF EXISTS TRANSPORTISTAS CASCADE;
DROP TABLE IF EXISTS NODOS CASCADE;
DROP TABLE IF EXISTS ENLACES CASCADE;
DROP TABLE IF EXISTS CLIENTES CASCADE;
DROP TABLE IF EXISTS CONTENEDORES CASCADE;
DROP TABLE IF EXISTS SOLICITUDES CASCADE;

DROP SEQUENCE IF EXISTS SEQ_TRAMOS;
DROP SEQUENCE IF EXISTS SEQ_RUTAS;
DROP SEQUENCE IF EXISTS SEQ_TARIFAS;
DROP SEQUENCE IF EXISTS SEQ_DEPOSITOS;
DROP SEQUENCE IF EXISTS SEQ_TRANSPORTISTAS;
DROP SEQUENCE IF EXISTS SEQ_NODOS;
DROP SEQUENCE IF EXISTS SEQ_ENLACES;
DROP SEQUENCE IF EXISTS SEQ_CLIENTES;
DROP SEQUENCE IF EXISTS SEQ_CONTENEDORES;
DROP SEQUENCE IF EXISTS SEQ_SOLICITUDES;

-- ============================================================================
-- Secuencias
-- ============================================================================
CREATE SEQUENCE SEQ_TRAMOS START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_RUTAS START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_TARIFAS START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_DEPOSITOS START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_TRANSPORTISTAS START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_NODOS START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_ENLACES START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_CLIENTES START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_CONTENEDORES START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_SOLICITUDES START WITH 1 INCREMENT BY 1;

-- ============================================================================
-- CLIENTES
-- ============================================================================
CREATE TABLE CLIENTES (
    CLI_ID      INT NOT NULL DEFAULT nextval('SEQ_CLIENTES'),
    NOMBRE      VARCHAR(255) NOT NULL,
    APELLIDO    VARCHAR(255) NOT NULL,
    DNI         INT NOT NULL,
    CORREO      VARCHAR(255) NOT NULL,
    DIRECCION   VARCHAR(255),
    TELEFONO    VARCHAR(20),
    ACTIVO      INT NOT NULL DEFAULT 1,
    CONSTRAINT PK_CLIENTES PRIMARY KEY (CLI_ID)
);

-- CONTENEDORES
CREATE TABLE CONTENEDORES (
    CONT_ID     INT NOT NULL DEFAULT nextval('SEQ_CONTENEDORES'),
    PESO        DOUBLE PRECISION NOT NULL,
    VOLUMEN     DOUBLE PRECISION NOT NULL,
    ESTADO      VARCHAR(50) NOT NULL,
    CLIENTE_ID  INT,
    CONSTRAINT FK_CONTENEDORES_CLIENTES FOREIGN KEY (CLIENTE_ID) REFERENCES CLIENTES(CLI_ID),
    CONSTRAINT PK_CONTENEDORES PRIMARY KEY (CONT_ID)
);

-- SOLICITUDES
CREATE TABLE SOLICITUDES (
    SOLI_ID          INT NOT NULL DEFAULT nextval('SEQ_SOLICITUDES'),
    ID_CLIENTE       INT NOT NULL,
    ID_CONTENEDOR    INT NOT NULL,
    ESTADO           VARCHAR(50) NOT NULL,
    COSTO_ESTIMADO   DOUBLE PRECISION,
    TIEMPO_ESTIMADO  INTEGER,
    FECHA_HORA_SALIDA TIMESTAMP,
    COSTO_FINAL      DOUBLE PRECISION,
    TIEMPO_REAL      INTEGER,
    CONSTRAINT FK_SOLICITUDES_CLIENTES FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTES(CLI_ID),
    CONSTRAINT FK_SOLICITUDES_CONTENEDORES FOREIGN KEY (ID_CONTENEDOR) REFERENCES CONTENEDORES(CONT_ID),
    CONSTRAINT PK_SOLICITUDES PRIMARY KEY (SOLI_ID)
);

-- ============================================================================
-- TRANSPORTISTAS
-- ============================================================================
CREATE TABLE TRANSPORTISTAS (
    TRANSP_ID   INT NOT NULL DEFAULT nextval('SEQ_TRANSPORTISTAS'),
    NOMBRE      VARCHAR(255) NOT NULL,
    APELLIDO    VARCHAR(255) NOT NULL,
    TELEFONO    VARCHAR(20),
    CORREO      VARCHAR(255) NOT NULL,
    DIRECCION   VARCHAR(255) NOT NULL,
    ACTIVO      BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT PK_TRANSPORTISTAS PRIMARY KEY (TRANSP_ID)
);

-- CAMIONES
CREATE TABLE CAMIONES (
    DOMINIO             VARCHAR(100) NOT NULL,
    ID_TRANSPORTISTA    INT NOT NULL,
    CAPACIDAD_PESO      DOUBLE PRECISION NOT NULL,
    CAPACIDAD_VOLUMEN   DOUBLE PRECISION NOT NULL,
    DISPONIBILIDAD      BOOLEAN NOT NULL,
    CONSUMO_BASE_X_KM   DOUBLE PRECISION NOT NULL,
    CONSUMO_X_KM        DOUBLE PRECISION NOT NULL,
    ACTIVO              INT NOT NULL DEFAULT 1,
    CONSTRAINT FK_CAMIONES_TRANSPORTISTAS FOREIGN KEY (ID_TRANSPORTISTA) REFERENCES TRANSPORTISTAS(TRANSP_ID),
    CONSTRAINT PK_CAMIONES PRIMARY KEY (DOMINIO)
);

-- TARIFAS
CREATE TABLE TARIFAS (
    TARIFA_ID           INT NOT NULL DEFAULT nextval('SEQ_TARIFAS'),
    VOLUMEN_MIN         DOUBLE PRECISION NOT NULL,
    VOLUMEN_MAX         DOUBLE PRECISION NOT NULL,
    COSTO_BASE_X_KM     DOUBLE PRECISION NOT NULL,
    CONSUMO_X_KM        DOUBLE PRECISION NOT NULL,
    PRECIO_COMBUSTIBLE  DOUBLE PRECISION NOT NULL,
    FECHA_DESDE         TIMESTAMP NOT NULL,
    FECHA_HASTA         TIMESTAMP,
    CONSTRAINT PK_TARIFAS PRIMARY KEY (TARIFA_ID)
);

-- DEPOSITOS
CREATE TABLE DEPOSITOS (
    DEPO_ID                 INT NOT NULL DEFAULT nextval('SEQ_DEPOSITOS'),
    NOMBRE                  VARCHAR(255) NOT NULL,
    DIRECCION               VARCHAR(255) NOT NULL,
    LATITUD                 DOUBLE PRECISION NOT NULL,
    LONGITUD                DOUBLE PRECISION NOT NULL,
    COSTO_ESTADIA_DIARIO    DOUBLE PRECISION NOT NULL,
    CONSTRAINT PK_DEPOSITOS PRIMARY KEY (DEPO_ID)
);

-- RUTAS
CREATE TABLE RUTAS (
    RUTA_ID                  INT NOT NULL DEFAULT nextval('SEQ_RUTAS'),
    ID_SOLICITUD             INT NOT NULL,
    ORIGEN_LATITUD           DOUBLE PRECISION NOT NULL,
    ORIGEN_LONGITUD          DOUBLE PRECISION NOT NULL,
    DESTINO_LATITUD          DOUBLE PRECISION NOT NULL,
    DESTINO_LONGITUD         DOUBLE PRECISION NOT NULL,
    CANTIDAD_TRAMOS          INT,
    CANTIDAD_DEPOSITOS       INT,
    CONSTRAINT PK_RUTAS PRIMARY KEY (RUTA_ID)
    -- CONSTRAINT FK_RUTAS_SOLICITUDES FOREIGN KEY (ID_SOLICITUD) REFERENCES SOLICITUDES(SOLI_ID)
);

-- TRAMOS
CREATE TABLE TRAMOS (
    TRAMO_ID            INT NOT NULL DEFAULT nextval('SEQ_TRAMOS'),
    ID_RUTA             INT NOT NULL,
    DOMINIO_CAMION      VARCHAR(100) NOT NULL,
    ORIGEN              INT,
    DESTINO             INT,
    ID_TARIFA           INT NOT NULL,
    ESTADO              VARCHAR(50) NOT NULL,
    DISTANCIA           DOUBLE PRECISION NOT NULL,
    TIEMPO_ESTIMADO     INTEGER NOT NULL,
    COSTO_APROXIMADO    DOUBLE PRECISION NOT NULL,
    COSTO_REAL          DOUBLE PRECISION,
    FECHA_HORA_INICIO   TIMESTAMP,
    FECHA_HORA_FIN      TIMESTAMP,
    CONSTRAINT PK_TRAMOS PRIMARY KEY (TRAMO_ID),
    CONSTRAINT FK_TRAMOS_RUTAS FOREIGN KEY (ID_RUTA) REFERENCES RUTAS(RUTA_ID),
    CONSTRAINT FK_TRAMOS_TARIFAS FOREIGN KEY (ID_TARIFA) REFERENCES TARIFAS(TARIFA_ID),
    CONSTRAINT FK_TRAMOS_ORIGEN FOREIGN KEY (ORIGEN) REFERENCES DEPOSITOS(DEPO_ID),
    CONSTRAINT FK_TRAMOS_DESTINO FOREIGN KEY (DESTINO) REFERENCES DEPOSITOS(DEPO_ID),
    CONSTRAINT FK_TRAMOS_CAMIONES FOREIGN KEY (DOMINIO_CAMION) REFERENCES CAMIONES(DOMINIO)
);

-- NODOS
CREATE TABLE NODOS (
    NODO_ID     INT NOT NULL DEFAULT nextval('SEQ_NODOS'),
    ID_DEPOSITO INT NOT NULL UNIQUE,
    LATITUD     DOUBLE PRECISION NOT NULL,
    LONGITUD    DOUBLE PRECISION NOT NULL,
    CONSTRAINT PK_NODOS PRIMARY KEY (NODO_ID),
    CONSTRAINT FK_NODOS_DEPOSITOS FOREIGN KEY (ID_DEPOSITO) REFERENCES DEPOSITOS(DEPO_ID)
);

-- ENLACES
CREATE TABLE ENLACES (
    ENLACE_ID       INT NOT NULL DEFAULT nextval('SEQ_ENLACES'),
    NODO_ORIGEN_ID       INT NOT NULL,
    NODO_DESTINO_ID      INT NOT NULL,
    DISTANCIA       DOUBLE PRECISION NOT NULL,
    TIEMPO_ESTIMADO INTEGER NOT NULL,
    CONSTRAINT PK_ENLACES PRIMARY KEY (ENLACE_ID),
    CONSTRAINT FK_ENLACES_ORIGEN FOREIGN KEY (NODO_ORIGEN_ID) REFERENCES NODOS(NODO_ID),
    CONSTRAINT FK_ENLACES_DESTINO FOREIGN KEY (NODO_DESTINO_ID) REFERENCES NODOS(NODO_ID)
);